### ISSUE TITLE
Vision Global. Panel 2. Otras fuentes de Ingresos

### ISSUE THREAD

**Issue by JoseLuisMorenoGomez** [OCM-Jerez/presupuestos-v14#37]
Al pasar con el cursor sobre el panel y éste expandirse, se pierde el ultimo renglón del texto
![issue2](https://user-images.githubusercontent.com/33074876/218441299-755bd1a7-7ba8-4795-b70a-386739cd2ccc.png)

**Comment by mamjerez** [comment]
Fix
