### ISSUE TITLE
Home. Botones sobre paneles principales de navegación

### ISSUE THREAD

**Issue by JoseLuisMorenoGomez** [OCM-Jerez/presupuestos-v14#38]
Al ir con el ratón sobre el botón, se pone a temblar antes de aparecer el botón de otro color y desplazado a la derecha, como se muestra en el recorte adjunto. Sería deseable evitar esta transición y el desplazamiento, dejando sólo el cambio de color,  
![issue3](https://user-images.githubusercontent.com/33074876/218442020-fc1b8e3d-36a7-40d6-a2a6-a12b7a73cb75.png)

**Comment by mamjerez** [comment]
Fix
