### ISSUE TITLE
Deprecation calc() in CSSS

### ISSUE THREAD

**Issue by mammam** [OCM-Jerez/presupuestos-v14#7]
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss?ngGlobalStyle - Warning: 
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13  strip-unit()
\src\app\scss\_mixins.scss 12:43    fluid-type()
..\..\styles.scss 64:5              root stylesheet

**Comment by mammam** [comment]
[webpack-dev-server] WARNING in ./src/styles.scss?ngGlobalStyle (./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss?ngGlobalStyle)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13  strip-unit()
\src\app\scss\_mixins.scss 12:43    fluid-type()
..\..\styles.scss 74:5              root stylesheet

logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING in ./src/app/layouts/footer/footer.component.scss?ngResource
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13            strip-unit()
\src\app\scss\_mixins.scss 12:43              fluid-type()
..\layouts\footer\footer.component.scss 35:9  root stylesheet

logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING in ./src/app/layouts/navbar/navbar.component.scss?ngResource
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13             strip-unit()
\src\app\scss\_mixins.scss 12:43               fluid-type()
..\layouts\navbar\navbar.component.scss 40:13  root stylesheet

logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING
C:\Users\Usuario\Google Drive\Angular\presupuestos-v14\src\app\app.module.ts depends on 'ag-grid-enterprise'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING
C:\Users\Usuario\Google Drive\Angular\presupuestos-v14\src\app\detalle-presupuesto\detalle-presupuesto.component.ts depends on 'highcharts/highcharts-more'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING
C:\Users\Usuario\Google Drive\Angular\presupuestos-v14\src\app\detalle-presupuesto\detalle-presupuesto.component.ts depends on 'highcharts/modules/heatmap'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING
C:\Users\Usuario\Google Drive\Angular\presupuestos-v14\src\app\detalle-presupuesto\detalle-presupuesto.component.ts depends on 'highcharts/modules/treemap'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
logger @ index.js:556
(anónimo) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anónimo) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Mostrar 6 marcos más
index.js:556 [webpack-dev-server] WARNING
C:\Users\Usuario\Google Drive\Angular\presupuestos-v14\src\app\hightcharts\prueba\prueba.component.ts depends on 'highcharts'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by mamjerez** [comment]
index.js:556 [webpack-dev-server] WARNING in ./src/app/indice/indice.component.scss?ngResource
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(32:5) autoprefixer: start value has mixed support, consider using flex-start instead

**Comment by mamjerez** [comment]
index.js:556 [webpack-dev-server] WARNING in ./src/app/layouts/navbar/navbar.component.scss?ngResource
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13                  strip-unit()
\src\app\scss\_mixins.scss 12:43                    fluid-type()
src\app\layouts\navbar\navbar.component.scss 98:17  root stylesheet

**Comment by mamjerez** [comment]
[webpack-dev-server] WARNING in ./src/app/layouts/footer/footer.component.scss?ngResource
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1) or calc($value / ($value * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

\src\app\scss\_functions.scss 2:13                 strip-unit()
\src\app\scss\_mixins.scss 12:43                   fluid-type()
src\app\layouts\footer\footer.component.scss 35:9  root stylesheet

logger @ index.js:556

**Comment by mamjerez** [comment]
Fix in commit b85df3a76a50044d92646cb368dc7f4ab72b6c91
